POST http://localhost:3333/users
content-type: application/json

{
    "email": "fred.kingstech@gmail.com",
    "fullName": "asd",
    "password": "asd",
    "phoneNumber": "asd",
    "role": "asd",
    "fromWhere": "asd",
    "companyName": "adsdds",
    "companyField": "asdsa",
    "companySize": "asdsa",
    "department": ["asdsa", "asddd"],
    "url": "asdsa"
}

###
POST https://agi-be-challenge.onrender.com/users
content-type: application/json

{
    "email": "fred.kingstech@gmail.com",
    "fullName": "asd",
    "password": "asd",
    "phoneNumber": "asd",
    "role": "asd",
    "fromWhere": "asd",
    "companyName": "adsdds",
    "companyField": "asdsa",
    "companySize": "asdsa",
    "department": ["asdsa", "asddd"],
    "url": "asdsa"
}

###
POST http://localhost:3333/sessions
content-type: application/json

{
    "email": "fred.kingstech@gmail.com",
    "password": "asd"
}

###
POST http://localhost:3333/validate
content-type: application/json

{
    "token": "79119c6a-98fa-47f6-9111-6cc757a2edf8"
}

###
GET http://localhost:3333/providers


###
GET http://localhost:3333/profile
Authorization: Bearer 
